// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmswkirjyslohtefihpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imptc3draXJqeXNsb2h0ZWZpaHBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzNjE2MTgsImV4cCI6MjA1MTkzNzYxOH0.PAfiN3z_w-0ZQlttGg97eBtMTLKHcibgVOMb7kPiHzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);